version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: phoenix
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080