<<<<<<< HEAD
version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix
      POSTGRES_DB: phoenix
    ports:
    - 5432:5432
=======
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: phoenix
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix
    ports: 
      - 5432:5432
>>>>>>> main
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080