version: '3.9'
services:
  init:
    image: phoenix-init:latest
    environment: 
      MIX_ENV: prod
      DATABASE_URL: ecto://phoenix:phoenix@db:5432/phoenix
      SECRET_KEY_BASE: JhhLO9oACpINDgzWo9xBWw+qKCrh7C6tzUhBo4rMGCbB51ssgPzZpkL812d12fL1
      PORT: 4000
    depends_on: 
      - db
  network:
    - chatter
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: phoenix
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix
    ports: 
      - 5432:5432
    network:
      - chatter
volumes:
  postgres:
    external: true
networks: 
  chatter:
    external: true