apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.deployment.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: chatter