kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30000
      hostPort: 30000
    - containerPort: 31000
      hostPort: 31000
- role: worker
- role: worker