name: Build and Push
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: phoenix
          POSTGRES_USER: phoenix
          POSTGRES_DB: phoenix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rallinator7
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 22.2.6
          elixir-version: 1.10.1
      - name: Run Unit Tests
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: ci:unitTest
      - name: Build Images
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: ci:build

      - name: Push Images to GHCR
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: ci:push